[workspace]

members = [
  "geo-glam-interop",
  "neo-aabb",
  "neo-coordinate-system",
  "neo-float",
  "neo-geo-boolops",
  "neo-intersection",
  "neo-line-segment",
  "neo-plane",
  "neo-ray",
  "neo-tessellation",
]

[workspace.dependencies]
# needed
float_next_after = { version = "1.0" }
geo = { version = "0.25", default-features = false }
glam = "0.24"
num-traits = { version = "0.2" }
spade = "2.2"

# workspace crates
geo-glam-interop = { path = "geo-glam-interop" }
neo-aabb = { path = "neo-aabb" }
neo-coordinate-system = { path = "neo-coordinate-system" }
neo-float = { path = "neo-float" }
neo-geo-boolops = { path = "neo-geo-boolops" }
neo-intersection = { path = "neo-intersection" }
neo-line-segment = { path = "neo-line-segment" }
neo-plane = { path = "neo-plane" }
neo-ray = { path = "neo-ray" }
neo-tessellation = { path = "neo-tessellation" }

# dev
geo-svg = "0.5"
paste = "1.0"
rand = "0.8"
serde_json = "1.0"

[patch.crates-io]
geo = { git = "https://github.com/RobWalt/geo", branch = "feat/falliable-boolops", default-features = false }
