[package]
name = "neo-tessellation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo.workspace = true
neo-float.workspace = true
spade = "2.2.0"
